version: "3"
services:
  app:
    command: ["bin/dev-server-starter", "bin/rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      - VIRTUAL_HOST=word_hoard.mancave.zzz
    volumes:
      - .:/app
      - bundle:/bundle

volumes:
  bundle:
